source ENV['GEM_SOURCE'] || "https://rubygems.org"
gemspec
gem 'CFPropertyList', '2.3.3'
gem 'addressable', '2.4.0'
gem 'aws-sdk-v1', '1.66.0'
gem 'beaker-answers', '0.11.0'
gem 'beaker-hiera', '0.1.1'
gem 'beaker-hostgenerator', '0.7.3'
gem 'beaker-pe', '0.11.0'
gem 'builder', '3.2.2'
gem 'coderay', '1.1.1'
gem 'deep_merge', '1.1.1'
gem 'diff-lcs', '1.2.5'
gem 'docile', '1.1.5'
gem 'docker-api', '1.31.0'
gem 'excon', '0.52.0'
gem 'fakefs', '0.9.1'
gem 'faraday', '0.9.2'
gem 'fission', '0.5.0'
gem 'fog', '1.34.0'
gem 'fog-atmos', '0.1.0'
gem 'fog-aws', '0.11.0'
gem 'fog-brightbox', '0.11.0'
gem 'fog-core', '1.42.0'
gem 'fog-dynect', '0.0.3'
gem 'fog-ecloud', '0.3.0'
gem 'fog-google', '0.0.9'
gem 'fog-json', '1.0.2'
gem 'fog-local', '0.3.0'
gem 'fog-powerdns', '0.1.1'
gem 'fog-profitbricks', '0.0.5'
gem 'fog-radosgw', '0.0.5'
gem 'fog-riakcs', '0.1.0'
gem 'fog-sakuracloud', '1.7.5'
gem 'fog-serverlove', '0.1.2'
gem 'fog-softlayer', '1.1.4'
gem 'fog-storm_on_demand', '0.1.1'
gem 'fog-terremark', '0.1.0'
gem 'fog-vmfusion', '0.1.0'
gem 'fog-voxel', '0.1.0'
gem 'fog-xml', '0.1.2'
gem 'formatador', '0.2.5'
gem 'google-api-client', '0.9.4'
gem 'googleauth', '0.5.1'
gem 'hocon', '1.1.2'
gem 'httpclient', '2.8.2.4'
gem 'hurley', '0.2'
gem 'in-parallel', '0.1.15'
gem 'inflecto', '0.0.2'
gem 'inifile', '2.0.2'
gem 'ipaddress', '0.8.3'
gem 'json', '1.8.3'
gem 'jwt', '1.5.4'
gem 'little-plugger', '1.1.4'
gem 'logging', '2.1.0'
gem 'memoist', '0.15.0'
gem 'method_source', '0.8.2'
gem 'mime-types', '2.99.3'
gem 'mini_portile2', '2.1.0'
gem 'minitest', '5.9.0'
gem 'multi_json', '1.12.1'
gem 'multipart-post', '2.0.0'
gem 'net-scp', '1.2.1'
gem 'net-ssh', '2.9.4'
gem 'nokogiri', '1.6.8'
gem 'open_uri_redirections', '0.2.1'
gem 'os', '0.9.6'
gem 'pkg-config', '1.1.7'
gem 'pry', '0.10.4'
gem 'rake', '10.5.0'
gem 'rbvmomi', '1.8.2'
gem 'representable', '2.3.0'
gem 'require_all', '1.3.3'
gem 'retriable', '2.1.0'
gem 'rspec', '3.5.0'
gem 'rspec-core', '3.5.3'
gem 'rspec-expectations', '3.5.0'
gem 'rspec-its', '1.2.0'
gem 'rspec-mocks', '3.5.0'
gem 'rspec-support', '3.5.0'
gem 'rsync', '1.0.9'
gem 'signet', '0.7.3'
gem 'simplecov', '0.12.0'
gem 'simplecov-html', '0.10.0'
gem 'slop', '3.6.0'
gem 'stringify-hash', '0.0.2'
gem 'thor', '0.19.1'
gem 'trollop', '2.1.2'
gem 'uber', '0.0.15'
gem 'unf', '0.1.4'
gem 'unf_ext', '0.0.7.2'
gem 'yard', '0.9.5'


# This section of the gemspec is for Puppet CI; it will pull in
# a supported beaker library for testing to overwrite the gemspec if
# a corresponding ENV var is found. Currently, the only supported lib
# is beaker-pe, which can be injected into the dependencies when the
# following ENV vars are defined: BEAKER_PE_PR_AUTHOR,
# BEAKER_PE_PR_COMMIT, BEAKER_PE_PR_REPO_URL. These correspond to the
# ghprb variables ghprbPullAuthorLogin, ghprbActualCommit,
# and ghprbAuthorRepoGitUrl respectively. In the "future", we should
# make this a standard format so we can pull in more than predefined
# variables.

if ENV['BEAKER_PE_PR_REPO_URL']
  lib = ENV['BEAKER_PE_PR_REPO_URL'].match(/\/([^\/]+)\.git$/)[1]
  author = ENV['BEAKER_PE_PR_AUTHOR']
  ref = ENV['BEAKER_PE_PR_COMMIT']
  gem lib, :git => "git@github.com:#{author}/#{lib}.git", :branch => ref
end
